# docker compose -f docker-compose.test.yml up --build --abort-on-container-exit

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_PORT: 8080
      MONGO_DB_CONNECTION_STRING: mongodb://auth_guard_admin_test:password_test@mongo:27017/testdb?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: super_53cr3t
    env_file:
      - .env.test
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    command: npm run test
    stdin_open: true
    tty: true

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: auth_guard_admin_test
      MONGO_INITDB_ROOT_PASSWORD: password_test
      MONGO_INITDB_DATABASE: testdb

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - 6379:6379

volumes:
  mongo-data:
